image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
install:
  - ECHO %APPVEYOR_BUILD_WORKER_IMAGE%
  - dotnet --version
  - dotnet restore
  - choco install googlechrome
build_script:
- dotnet build
- npm -g install npm@latest
- cd src\AngularWebpackVisualStudio
- npm install
- npm run build-production
- npm run build-dev
before_build:
- appveyor-retry dotnet restore -v Minimal
test_script:
- npm test
- cd C:\projects\angular2webpackvisualstudio\tests\AngularWebpackVisualStudio_Tests
- dotnet test
